#!/bin/bash
source /etc/os-release
BACKTITLE="March7th's Alarm Utility"

add_source() {
if [[ $NAME == "Manjaro-ARM" ]]; then
	dialog --title "WARNING" --msgbox "Seems You are running Manjaro.\nThese sources are prepared for Arch Linux and SOME might can't run normally on Manjaro.\nIf you encountered error and want to get some help, please tell the people help you that you are using Manjaro." 10 60
fi

REPO=$(dialog --backtitle "${BACKTITLE}" --title "Add Extra Repos" --checklist \
"These Binary repos contains some prebuild extra softwares from AUR or elsewhere.\nOn ARM machines they are very useful because former usually got a weak CPU." 15 100 3 \
"ArchLinuxCN" "Arch Linux Chinese Communtiy Repo" OFF \
"Clansty" "Clansty's Personal Repo" OFF 3>&1 1>&2 2>&3)

if grep -q  "ArchLinuxCN" < /etc/pacman.conf || echo "$REPO" | grep -q "ArchLinuxCN"; then
	INSTALL=true
	cat >> "/etc/pacman.conf" <<'EOF'

[archlinuxcn]
SigLevel = Never
Server = https://mirrors.tuna.tsinghua.edu.cn/archlinuxcn/$arch
EOF
	if grep -q  "Clansty" < /etc/pacman.conf || echo "$REPO" | grep -q "Clansty"; then
		INSTALL=true
		cat >> "/etc/pacman.conf" <<'EOF'

[Clansty]
SigLevel = Never
#Server = https://repo.lwqwq.com/archlinux/$arch
Server = https://pacman.ltd/archlinux/$arch
Server = https://repo.clansty.com/archlinux/$arch
EOF
    fi
    else
    main_menu
fi

if [[ INSTALL == true ]] ; then
	dialog --title "OK" --msgbox "Successfully added repo $REPO." 10 60
	main_menu
else
	dialog --title "OK" --msgbox "Repo $REPO was not added.\nMaybe it is already added." 10 60
	main_menu
fi
}

part_grow() {
if bash -c "compgen -ac" | grep -q growpart ; then
   echo -e "Installing Necesscary tools..."
   pacman -Sy cloud-guest-utils xfsprogs btrfs-progs
fi

# Where's your root~~~
ROOT_PT="$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')"
if [[ -z "${ROOT_PT}" ]]; then
	dialog --title "ERROR" --msgbox "Cannot find the physical partition of your root file system." 8 60
	main_menu
fi

echo -e "Expanding Physical Partition ... "
growpart /dev/${DISK_NAME} 2

echo -e "Expanding file system ... " 
ROOTFS_TYPE="$(df -hT / | grep "/" | awk '{print $2}')"
if [[ "${ROOTFS_TYPE}" == "btrfs" ]]; then
	echo -e "Your root file system is Btrfs."
	btrfs filesystem resize max /
	dialog --title "OK" --msgbox "Expanded Your root file system." 8 60
	main_menu
elif [[ "${ROOTFS_TYPE}" == "ext4" ]]; then
	echo -e "Your root file system is ext4."
    resize2fs /dev/${ROOT_PTNAME}
    dialog --title "OK" --msgbox "Expanded Your root file system." 8 60
    main_menu
else
	dialog --title "ERROR" --msgbox "Your root partition doesn't contains a file system supported by the script.\nWe only support ext4 and Btrfs. But you have a ${ROOTFS_TYPE} file system. You are on your own." 8 90
	main_menu
fi
}

install_desktop() {
if [[ $NAME == "Manjaro-ARM" ]]; then
	dialog --title "WARNING" --msgbox "Seems You are running Manjaro.\nManjaro images has desktop preinstalled.\nSo you dont need this." 10 60

fi

DE=$(dialog --backtitle "${BACKTITLE}" --title "Install Desktop" --menu  "Which desktop do you like?" 15 100 4 \
"KDE Plasma" "Highly customizable, Releatively Low system resource consumption" \
"GNOME" "Clean, Simple and easy to use, but less customizable." \
"deepin" "Most Beautiful at default, Least customizable" \
"Xfce" "Least system resource consumption, Highly customizable but ugly out of box" \
"Back to Main Menu" "" 3>&1 1>&2 2>&3 )

if [[ "${DE}" == "KDE Plasma" ]]; then
	echo -e "Installing KDE Plasma Desktop..."
	pacman -Sy plasma kde-utilities kde-graphics firefox
elif [[ "${DE}" == "GNOME" ]]; then
	echo -e "Installing GNOME Desktop..."
	pacman -Sy gnome gnome-extra firefox
elif [[ "${DE}" == "deepin" ]]; then
	echo -e "Installing deepin Desktop..."
	pacman -Sy deepin deepin-kwin deepin-extra firefox
elif [[ "${DE}" == "Xfce" ]]; then
	echo -e "Installing Xfce Desktop..."
	pacman -Sy xfce4 xfce4-goodies firefox
elif [[ "${DE}" == "Back to Main Menu" ]]; then
	main_menu
else
	main_menu
fi
}

extra() {
CHOOSE_E=$(dialog --backtitle "${BACKTITLE}" --title "Extra Menu" --menu "Choose an option" 25 78 4 \
"Switch to Chinese Mirror" "" \
"Install Chinese IM" "" \
"Install Bluetooth Support" "" \
"Switch to Chinese Mirror" "" \
"Back" "" 3>&1 1>&2 2>&3 )

if [[ "${CHOOSE_E}" == "Switch to Chinese Mirror" ]]; then

	rm -rf /etc/pacman.d/mirrorlist
	cat >> /etc/pacman.d/mirrorlist <<'EOF'
Server = https://mirrors.ustc.edu.cn/archlinuxarm/$arch/$repo
Server = https://mirrors.tuna.tsinghua.edu.cn/archlinuxarm/$arch/$repo
Server = https://repo.huaweicloud.com/archlinuxarm/$arch/$repo
Server = http://mirror.lzu.edu.cn/archlinuxarm/$arch/$repo
EOF
	pacman -Sy
	dialog --title "OK" --msgbox "Switched Your Repo Mirror to Chinese mirror." 10 60

elif [[ "${CHOOSE_E}" == "Install Chinese IM" ]]; then

	pacman -Sy fcitx5-im fcitx5-chinese-addons fcitx5-pinyin-moegirl fcitx5-material-color fcitx5-rime
	cat >> ~/.pam_environment <<'EOF'
INPUT_METHOD DEFAULT=fcitx5
GTK_IM_MODULE DEFAULT=fcitx5
QT_IM_MODULE DEFAULT=fcitx5
XMODIFIERS DEFAULT=\@im=fcitx5
SDL_IM_MODULE DEFAULT=fcitx
EOF
	dialog --title "OK" --msgbox "Installed Chinese IM,but it needs further configration.\nSee https://arch.icekylin.online/rookie/desktop-env-and-app.html#_10-安装输入法" 10 60

elif [[ "${CHOOSE_E}" == "Install Bluetooth Support" ]]; then

	pacman -Sy bluez bluez-utils pulseaudio-bluetooth
	systemctl enable --now bluetooth
	dialog --title "OK" --msgbox "If you have bluetooth, it should be enabled now." 10 60

elif [[ "${CHOOSE_E}" == "Back" ]]; then
	main_menu
else
	main_menu
fi
}


main_menu() {
CHOOSE=$(dialog --backtitle "${BACKTITLE}" --title "Main Menu" --menu "Choose an option" 25 78 4 \
"Install Desktop" "Choose a Desktop to install" \
"Expand Partition" "Expand your root Partition" \
"Add extra repo" "Some Extra Binary Repo" \
"Some Extra Features" "" \
"Exit" "" 3>&1 1>&2 2>&3 )

if [[ "${CHOOSE}" == "Install Desktop" ]]; then
	install_desktop
elif [[ "${CHOOSE}" == "Expand Partition" ]]; then
	part_grow
elif [[ "${CHOOSE}" == "Add extra repo" ]]; then
	add_source
elif [[ "${CHOOSE}" == "Some Extra Features" ]]; then
	extra
elif [[ "${CHOOSE}" == "Exit" ]]; then
	exit 0
fi
}

if [[ $NAME != "Arch Linux ARM" ]]; then
	echo -e "Your distro is not supported by the script."
	exit 1
elif [ $EUID != 0 ];then
        echo "Please Run This Script As root"
        exit 1
fi
main_menu
